// ...previous code...

const options = {
  // ...other options...
  waitUntil: "domcontentloaded"
};

// ...previous code...

const tourism = {
  // ...other properties...
  waitMs: 8000
};

// ...following code...